name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        uses: ./.github/actions/build

      - name: Upload native library
        uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.os }}
          path: |
            dist/*.so
            dist/*.dylib
            dist/*.dll
          if-no-files-found: error
